### ISSUE TITLE
Please this can be added to BitcoinZ or Zcash based coins ?

### ISSUE THREAD

**Issue by miranos** [zawy12/difficulty-algorithms#29]
Hi,

Is there a way to implement it on BitcoinZ coin ?

Knowing that it is based on Zcash.

Thank you

**Comment by zawy12** [comment]
Zcash is based on BTC.  The LWMA shows the BTC code as done by BTC gold which is based on Zcash.  There are others.
    On Saturday, June 9, 2018, 1:38:54 PM EDT, miranos <notifications@github.com> wrote:  
 
 
Hi,

Is there a way to implement it on BitcoinZ coin ?

Knowing that it is based on Zcash.

Thank you
